# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codingquark
email: dhavan@hey.com
description: > # this means to ignore newlines until "baseurl:"
  My hacking adventures
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codingquark.com" # the base hostname & protocol for your site
github_username:  codingquark
twitter_username: codingquark
mastodon_username: codingquark
mastodon_profile: https://mathstodon.xyz/@codingquark
git_repository_path: https://github.com/codingquark/codingquark.github.io/tree/master

# Build settings
markdown: kramdown

# Feed settings
plugins:
  - jekyll-feed

assets:
   sources:
       - assets/fonts
